=== tangly-team/tangly-os/net.tangly.erp.invoices/src/main/resources/invoice-schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "title": "invoice archive schema",
    "description": "schema to describe invoices",
    "definitions": {
        "address": {
            "type": "object",
            "properties": {
                "street": {
                    "type": "string"
                },
                "extended": {
                    "type": "string"
                },
                "locality": {
                    "type": "string"
                },
                "postCode": {
                    "type": "string"
                },
                "region": {
                    "type": "string"
                },
                "country": {
                    "type": "string"
                }
            }
        },
        "legalEntity": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "vatNr": {
                    "type": "string"
                },
                "address": {
                    "$ref": "#/definitions/address"
                },
                "email": {
                    "type": "string",
                    "format": "email"
                },
                "emailccs": {
                    "type": "array",
                    "items": {
                        "type": "string",
                        "format": "email"
                    }
                }
            },
            "required": [
                "id",
                "name",
                "address"
            ],
            "additionalProperties": false
        },
        "bankConnection": {
            "type": "object",
            "description": "bank connection information to perform a money transfer",
            "properties": {
                "iban": {
                    "type": "string"
                },
                "bic": {
                    "type": "string"
                },
                "institute": {
                    "type": "string"
                }
            },
            "required": [
                "iban"
            ]
        },
        "article": {
            "type": "object",
            "description": "article sold and invoiced with a standard price and VAT rate",
            "properties": {
                "id": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "unitPrice": {
                    "type": "string"
                },
                "unit": {
                    "type": "string"
                }
            },
            "required": [
                "id",
                "unitPrice",
                "unit"
            ],
            "additionalProperties": false
        },
        "invoiceLine": {
            "type": "object",
            "properties": {
                "position": {
                    "type": "integer",
                    "minimum": 1
                },
                "text": {
                    "type": "string"
                }
            },
            "required": [
                "position",
                "text"
            ]
        },
        "invoiceItem": {
            "type": "object",
            "allOf": [
                {
                    "$ref": "#/definitions/invoiceLine"
                },
                {
                    "properties": {
                        "article": {
                            "$ref": "#/definitions/article"
                        },
                        "quantity": {
                            "type": "string"
                        },
                        "vatRate": {
                            "type": "string"
                        }
                    },
                    "required": [
                        "quantity",
                        "vatRate"
                    ]
                }
            ]
        },
        "invoiceSubtotal": {
            "type": "object",
            "allOf": [
                {
                    "$ref": "#/definitions/invoiceLine"
                },
                {
                    "properties": {
                        "items": {
                            "type": "array",
                            "items": {
                                "type": "number",
                                "minimum": 0
                            },
                            "minItems": 1,
                            "uniqueItems": true
                        }
                    },
                    "required": [
                        "items"
                    ]
                }
            ]
        }
    },
    "type": "object",
    "properties": {
        "id": {
            "description": "unique identifier of the invoice",
            "type": "string"
        },
        "name": {
            "type": "string"
        },
        "contractId": {
            "type": "string"
        },
        "invoicingEntity": {
            "$ref": "#/definitions/legalEntity"
        },
        "invoicingConnection": {
            "$ref": "#/definitions/bankConnection"
        },
        "invoicedEntity": {
            "$ref": "#/definitions/legalEntity"
        },
        "deliveryDate": {
            "type": "string",
            "format": "date"
        },
        "invoiceDate": {
            "type": "string",
            "format": "date"
        },
        "dueDate": {
            "type": "string",
            "format": "date"
        },
        "currency": {
            "type": "string"
        },
        "locale": {
            "type": "string"
        },
        "text": {
            "type": "string"
        },
        "paymentConditions": {
            "type": "string"
        },
        "items": {
            "type": "array",
            "items": {
                "anyOf": [
                    {
                        "$ref": "#/definitions/invoiceItem"
                    },
                    {
                        "$ref": "#/definitions/invoiceSubtotal"
                    }
                ]
            },
            "minItems": 1
        }
    },
    "required": [
        "id",
        "name",
        "contractId",
        "invoicingEntity",
        "invoicedEntity",
        "invoiceDate",
        "dueDate",
        "currency"
    ],
    "additionalProperties": false
}

=== tangly-team/tangly-os/net.tangly.erp-integration/src/main/resources/net/tangly/invoices/2017/2017-8022-Invoice-HSLU-December.json
{
    "invoicingConnection": {
        "iban": "CH88 0900 0000 3064 1768 2",
        "institute": "Postfinanz Schweiz",
        "bic": "POFICHBEXXX"
    },
    "dueDate": "2017-01-07",
    "paymentConditions": "30 days net",
    "invoiceDate": "2016-12-07",
    "invoicingEntity": {
        "vatNr": "CHE-357.875.339 MWST",
        "name": "tangly llc",
        "id": "CHE-357.875.339",
        "address": {
            "country": "CH",
            "street": "Lorzenhof 27",
            "locality": "Cham",
            "postCode": "6330",
            "region": "ZG"
        },
        "email": "info@tangly.net"
    },
    "invoicedEntity": {
        "name": "Lucerne School of Information Technology",
        "id": "CHE-302.967.535",
        "address": {
            "poBox": "Postfach",
            "country": "CH",
            "street": "Technikumstrasse 21",
            "locality": "Horw",
            "postCode": "6048",
            "region": "ZG",
            "extended": "z.H. John Doe"
        },
        "email": "finances@hslu.ch"
    },
    "name": "2017-8022-Invoice-HSLU-December",
    "contractId": "HSLU-2015",
    "currency": "CHF",
    "locale": "de",
    "id": "2017-8022",
    "text": "Vorlesung ENAPP Architektur 2017-12-07",
    "items": [
        {
            "article": {
                "unitPrice": "190",
                "unit": "hour",
                "description": "Agile training at recognized technical university",
                "id": "5002"
            },
            "quantity": "3",
            "position": 1,
            "vatRate": "0.0",
            "text": "Vorlesung Modul ENAPP Architecture\u201c - Kotr/Kost 110083-00"
        }
    ]
}

=== tangly-team/tangly-os/net.tangly.erp-integration/src/main/resources/net/tangly/invoices/2020/2020-8001-Invoice-HSLU-May.json
{
    "invoicingConnection": {
        "iban": "CH88 0900 0000 3064 1768 2",
        "institute": "Postfinanz Schweiz",
        "bic": "POFICHBEXXX"
    },
    "dueDate": "2020-06-30",
    "paymentConditions": "30 days net",
    "invoiceDate": "2020-06-30",
    "invoicingEntity": {
        "vatNr": "CHE-357.875.339 MWST",
        "name": "tangly llc",
        "id": "CHE-357.875.339",
        "address": {
            "country": "CH",
            "street": "Lorzenhof 27",
            "locality": "Cham",
            "postCode": "6330",
            "region": "ZG"
        },
        "email": "info@tangly.net"
    },
    "invoicedEntity": {
        "name": "Lucerne School of Information Technology",
        "id": "CHE-302.967.535",
        "address": {
            "poBox": "Postfach",
            "country": "CH",
            "street": "Technikumstrasse 21",
            "locality": "Horw",
            "postCode": "6048",
            "region": "ZG",
            "extended": "z.H. John Doe"
        },
        "email": "finances@hslu.ch",
        "emailccs": [
            "john.doe@hslu.ch"
        ]
    },
    "name": "2020-8001-Invoice-HSLU-May",
    "contractId": "HSLU-2020",
    "currency": "CHF",
    "locale": "de",
    "id": "2020-8001",
    "text": "Vorlesung Software Architecture and Techniques SWAT 2020-02-22 bis 2020-05-31 basierend auf Vertragsbest√§tigung vom 05 Februar 2020",
    "items": [
        {
            "article": {
                "unitPrice": "190",
                "unit": "hour",
                "description": "Agile training at recognized technical university",
                "id": "5002"
            },
            "quantity": "49",
            "vatRate": "0.0",
            "position": 1,
            "text": "Vorlesung Software Architecture and Techniques (Kost/Kotr 160\u2019000)"
        }
    ]
}

=== tangly-team/tangly-os/net.tangly.erp-integration/src/main/resources/net/tangly/invoices/2017/2017-8001-Invoice-HSLU-February.json
{
    "invoicingConnection": {
        "iban": "CH88 0900 0000 3064 1768 2",
        "institute": "Postfinanz Schweiz",
        "bic": "POFICHBEXXX"
    },
    "dueDate": "2017-02-28",
    "paymentConditions": "30 days net",
    "invoiceDate": "2017-01-25",
    "invoicingEntity": {
        "vatNr": "CHE-357.875.339 MWST",
        "name": "tangly llc",
        "id": "CHE-357.875.339",
        "address": {
            "country": "CH",
            "street": "Lorzenhof 27",
            "locality": "Cham",
            "postCode": "6330",
            "region": "ZG"
        },
        "email": "info@tangly.net"
    },
    "invoicedEntity": {
        "name": "Lucerne School of Information Technology",
        "id": "CHE-302.967.535",
        "address": {
            "poBox": "Postfach",
            "country": "CH",
            "street": "Technikumstrasse 21",
            "locality": "Horw",
            "postCode": "6048",
            "region": "ZG",
            "extended": "z.H. John Doe"
        },
        "email": "finances@hslu.ch"
    },
    "name": "2017-8001-Invoice-HSLU-February",
    "contractId": "HSLU-2015",
    "currency": "CHF",
    "locale": "de",
    "id": "2017-8001",
    "text": "Kurzeinsatz in der Weiterbildung 2016-10-15",
    "items": [
        {
            "article": {
                "unitPrice": "200",
                "unit": "hour",
                "description": "Agile training at recognized technical university",
                "id": "5003"
            },
            "quantity": "1",
            "vatRate": "0.0",
            "position": 1,
            "text": "Pauschalentschädigung für Expertinnen und Experten (mündliche Modulendprüfung inkl. Spesen)"
        },
        {
            "article": {
                "unitPrice": "25",
                "unit": "unit",
                "description": "Examination work per student",
                "id": "5004"
            },
            "quantity": "20",
            "vatRate": "0.0",
            "position": 2,
            "text": "Studenten mündliche Prüfung"
        },
        {
            "position": 3,
            "text": "Test subtotal",
            "items": [
                1,
                2
            ]
        }
    ]
}

=== tangly-team/tangly-os/net.tangly.erp-integration/src/main/resources/net/tangly/invoices/2019/2019-8020-Invoice-HSLU-December.json
{
    "invoicingConnection": {
        "iban": "CH88 0900 0000 3064 1768 2",
        "institute": "Postfinanz Schweiz",
        "bic": "POFICHBEXXX"
    },
    "invoicedEntity": {
        "name": "Lucerne School of Information Technology",
        "id": "CHE-302.967.535",
        "address": {
            "poBox": "Postfach",
            "country": "CH",
            "street": "Technikumstrasse 21",
            "locality": "Horw",
            "postCode": "6048",
            "region": "ZG",
            "extended": "z.H. John Doe"
        },
        "email" : "finances@hslu.ch"
    },
    "contractId": "HSLU-2015",
    "dueDate": "2020-01-08",
    "paymentConditions": "30 days net",
    "currency": "CHF",
    "locale": "de",
    "id": "2019-8020",
    "name": "2019-8020-Invoice-HSLU-November",
    "text": "Vorlesung ENAPP Agile Architektur 2019-12-05",
    "invoiceDate": "2019-12-07",
    "items": [
        {
            "article": {
                "unitPrice": "190",
                "unit": "hour",
                "description": "Agile training at recognized technical university",
                "id": "5002"
            },
            "quantity": "3",
            "vatRate": "0.0",
            "position": 1,
            "text": "Vorlesung Modul ENAPP Architecture"
        }
    ],
    "invoicingEntity": {
        "vatNr": "CHE-357.875.339 MWST",
        "name": "tangly llc",
        "id": "CHE-357.875.339",
        "address": {
            "country": "CH",
            "street": "Lorzenhof 27",
            "locality": "Cham",
            "postCode": "6330",
            "region": "ZG"
        },
        "email": "info@tangly.net"
    }
}
